tutored/djangolearn/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
	path('polls/', include('polls.urls')),
]

tutored/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

'''
path(route, view, kwargs, name)


'''

tutored/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)



class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

tutored/polls/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render

from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    
    template = 'polls/index.html'
    context = {
        'latest_question_list': latest_question_list,
    }

    #return HttpResponse(template.render(context, request))
    return render(request, template, context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except:
        raise Http404("Question does not exist")

    template = 'polls/detail.html'
    context = {
        'question': question,
    }

    #return HttpResponse("You're looking at question %s." % question_id)
    return render(request, template, context)

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    numArray = {1, 5, 6, 7, 9}
    title = 'uwu'

    template = 'polls/vote.html'
    context = {
        'numArray': numArray,
        'title': title,
    }

    #return HttpResponse("You're voting on question %s." % question_id)
    return render(request, template, context)

tutored/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
	{% for choice in question.choice_set.all %}
    	<li>{{ choice.choice_text }}</li>
	{% endfor %}
</ul>

tutored/polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
	<title>Yes.</title>
</head>
<body>
	{%if latest_question_list%}
		<ul>
			{%for question in latest_question_list%}
				<li><a href="/polls/{{ question.id }}/">
				{{ question.question_text }}</a></li>
				<li><a href="{% url 'detail' question.id %}">
				{{ question.question_text }}</a></li>
			{%endfor%}
		</ul>
	{%else%}
		<p>No polls are available.</p>
	{%endif%}
</body>
</html>

tutored/polls/templates/polls/vote.html
<head>
	<title>{{title}}</title>
</head>

<body>
	<ul>
		{% for num in numArray %}
			<li>{{num}}</li>
		{% endfor %}
	</ul>	
</body>